// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQMLWzcJl3y_zNIPKcuphiMxdGsUnztY',
    appId: '1:233834917651:web:19c46c31dd9c34daa634e6',
    messagingSenderId: '233834917651',
    projectId: 'veterinariapandy-73c5d',
    authDomain: 'veterinariapandy-73c5d.firebaseapp.com',
    storageBucket: 'veterinariapandy-73c5d.firebasestorage.app',
    measurementId: 'G-47ZW2TV6EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_HoZfIPvuvxvDGAVfpdr73MK3JLdyLgc',
    appId: '1:233834917651:android:8be2f38945ca4f32a634e6',
    messagingSenderId: '233834917651',
    projectId: 'veterinariapandy-73c5d',
    storageBucket: 'veterinariapandy-73c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAj7ldqnoSZ7hamnne29NIbhFVIA4VGVk',
    appId: '1:233834917651:ios:ba3d602a38f327a9a634e6',
    messagingSenderId: '233834917651',
    projectId: 'veterinariapandy-73c5d',
    storageBucket: 'veterinariapandy-73c5d.firebasestorage.app',
    iosBundleId: 'com.example.veterinariaPandy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAj7ldqnoSZ7hamnne29NIbhFVIA4VGVk',
    appId: '1:233834917651:ios:ba3d602a38f327a9a634e6',
    messagingSenderId: '233834917651',
    projectId: 'veterinariapandy-73c5d',
    storageBucket: 'veterinariapandy-73c5d.firebasestorage.app',
    iosBundleId: 'com.example.veterinariaPandy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjQMLWzcJl3y_zNIPKcuphiMxdGsUnztY',
    appId: '1:233834917651:web:19c46c31dd9c34daa634e6',
    messagingSenderId: '233834917651',
    projectId: 'veterinariapandy-73c5d',
    authDomain: 'veterinariapandy-73c5d.firebaseapp.com',
    storageBucket: 'veterinariapandy-73c5d.firebasestorage.app',
    measurementId: 'G-47ZW2TV6EL',
  );
}
